Start work on copy(), and switch to ints in main() to make errors less cryptic than the following:
stack.cpp:78: error: no matching function for call to
‘exscape::stack<std::basic_string<char, std::char_traits<char>,
std::allocator<char> > >::copy(exscape::stack<std::basic_string<char,
std::char_traits<char>, std::allocator<char> > >* const, const
exscape::stack<std::basic_string<char, std::char_traits<char>,
std::allocator<char> > >&)’
stack.cpp:52: note: candidates are: static void
exscape::stack<Type>::copy(exscape::stack<Type>&, const
exscape::stack<Type>&) [with Type = std::basic_string<char,
std::char_traits<char>, std::allocator<char> >]